### ISSUE TITLE
برای نمودار وزن با توجه به درخواست مشتری ها باید بجای نمایش روزانه تقویم گذاشته شود تا دادهای روزهای قبل نیز نمایش داده شود

### ISSUE THREAD

**Issue by mirmostafa** [Moshaveran-IoT/GsTechCoreV1-GitLab#195]

**Comment by mirmostafa** [comment]
با توجه به دستور دکتر کاووسی، (@Akavoosi )، برای افزودن تقویم به نمودار وزن در مانیتورینگ، با توجه به صحبتهای صورت گرفته، به این نتیجه رسیدیم که به جای بارگذاری اضافی بر روی صفحه مانیتورینگ، می‌توانیم کاربر را به صفحه گزارش وزن هدایت کنیم. به این ترتیب، کاربر می‌تواند با کلیک بر روی هر نقطه از نمودار، به صفحه گزارش وزن منتقل شود و ما گزارش را بر اساس اطلاعات مربوط به آن نقطه خاص پر خواهیم کرد.

این روش به ما این امکان را می‌دهد که داده‌های تاریخ‌های گذشته را به صورت منظم نمایش دهیم و تجربه کاربری بهتری را فراهم کنیم. همچنین با این رویکرد، بار اضافی بر روی صفحه مانیتورینگ کاهش می‌یابد و امکان مدیریت بهتر داده‌ها فراهم می‌شود.

لطفاً اگر نظری دارید، به اشتراک بگذارید. تا بررسی و عملیاتی کنیم.

**Comment by Maedehoseyni** [comment]
برای تب های مانیتورینگ به ازای هر تب گزارش مخصوص برای تاریخ های متفاوت قابل مشاهده است

**Comment by Maedehoseyni** [comment]
قرار بر این شد که به گزارش وزن وصل شود و از اونجا گزارش بگیرد
