### ISSUE TITLE
اشتباه محاسبه شدن مدت زمان پایان سفر 

### ISSUE THREAD

**Issue by mirmostafa** [Moshaveran-IoT/GsTechCoreV1-GitLab#216]
در گزارش سفر نقطه پایان هم بر اساس سرعت و هم بر اساس GPS  باید داده شود(بخاطر مشکل قطعی GPS) بخاطر درست نشان ندادن مکان در گزارش سفر که این موضوع باعث شده زمان پایان سفر نامحدود باشد که بارها توسط مشتریان گوشزد شد است.

به بیان دیگر چون gps در حال ارسال دیتا میباشد (درصورتیکه خودرو ساعتهاست که به مکان برگشته) این امر باعث می شود تا ساعت 12 شب سفر ادامه داشته باشد که قطعا اشتباه است.

(نیاز به گفتگو در این زمینه بصورت تیمی می باشد)

![Image](https://github.com/Moshaveran-IoT/GSTechV3/assets/134223340/088ab9bb-6bed-4e8f-b0de-e6453b4f932f)

**Comment by Akavoosi** [comment]
مشکل پا برجاست 

![Image](https://github.com/user-attachments/assets/6db4c54b-b849-4ad3-ab02-087107b42109)

**Comment by Akavoosi** [comment]
مقرر شد که مدت زمان توقف نیز نشان داده شود و در نهایت میزان دقیق رانندگی راننده

**Comment by Maedehoseyni** [comment]
- [ ] فاصله نقاط به 150 متر تغییر بافت 
- [ ] محاسبه زمان درست شد
