### ISSUE TITLE
مشکل در ثبت سرعت غیر مجاز

### ISSUE THREAD

**Issue by mirmostafa** [Moshaveran-IoT/GsTechCoreV1-GitLab#253]
در قسمت سرعت غیر مجاز چندین بار سرعت غیرمجاز را حتی بصورت ثانیه ای نمایش می دهد که باید برایش محدودیت و یا تایم تعریف شود.
به عنوان مثال در یک دقیقه 5 بار آلارم سرعت غیر مجاز داده نشود مثلا بگوید در فلان دقیقه شروع شده و تا فلان دقیقه این سرعت غیر مجاز ادامه داشته و سپس با کلیک کردن روی آن میران سرعتهای غیر مجاز نمایش داده شود.

**Comment by mirmostafa** [comment]
جناب دکتر کاووسی @Akavoosi 
آیا این مورد انجام شده؟

**Comment by Akavoosi** [comment]
مشکل حل شده است 
تشکر
