### ISSUE TITLE
خطا در نمایش تعداد ماشینهای داشبورد 

### ISSUE THREAD

**Issue by Akavoosi** [Moshaveran-IoT/GsTechCoreV1-GitLab#406]
### Repro Steps

1- در صفحه داشبورد تعداد ماشینها را اشتباه نمایش می دهد
2- برخی ماشینها را در مانیتورینگ چند بار نمایش می دهد.

**Comment by Akavoosi** [comment]
همچنان مشکل دارد جمع اعداد یکی نیست!

**Comment by Maedehoseyni** [comment]
مانیتورینگ زرد ها را حساب نمی کرد درست شد
