### ISSUE TITLE
انتقال دیتاهای کن کربنات

### ISSUE THREAD

**Issue by Akavoosi** [Moshaveran-IoT/GsTechCoreV1-GitLab#409]
### Description

انتقال دیتاهای کن کربنات در اسرع وقت انجام شود چون روز به روز سنگینتر می شوند.

**Comment by mirmostafa** [comment]
# Tasks List

- [ ] نوشتن script مربوطه

**Comment by mirmostafa** [comment]
# Tasks List

- [ ] نوشتن script مربوطه

**Comment by mirmostafa** [comment]
ایشوی مربوطه: [#425 ](https://github.com/Moshaveran-IoT/GsTechCoreV1-GitLab/issues/425)
