### ISSUE TITLE
الزامی نمودن فیلدهای معرفی خودرو

### ISSUE THREAD

**Issue by Akavoosi** [Moshaveran-IoT/GsTechCoreV1-GitLab#422]
### Repro Steps

![Image](https://github.com/user-attachments/assets/d80309b8-8d5d-4d0f-bf92-06f8d48fa037)

**Comment by Akavoosi** [comment]
هر 4 فیلد باید الزامی باشند وگرنه خطا بدهد و اجازه ثبت ندهد

**Comment by mirmostafa** [comment]
کار، سمت back انجام شد. در انتظار تکمیل در از سمت @Moshaveran-IoT/front-end هستم.

**Comment by Maedehoseyni** [comment]
فیلد راننده نباید اجباری باشد چون می توان از تغییر و تحولان شروع به ثبت راننده گرفت و یا ماشین بدون راننده ثبت کرد

**Comment by mirmostafa** [comment]
انجام شد.
