### ISSUE TITLE
گزارش وزن بر اساس کشنده نیز ارایه گردد

### ISSUE THREAD

**Issue by Akavoosi** [Moshaveran-IoT/GsTechCoreV1-GitLab#423]
### Repro Steps

با توجه به اینکه در حال حاضر گزارش وزن بر اساس 
axel load sum 
 در تریلر نمایش داده می شود اما برخی از مشتریان ما کشنده دارند که بر اساس عدد وزن 1 و2و3 در کشنده( در قسمت ای سی یو) نمایش داده می شود 
پس گزارش وزن در کشنده را باید به این پارامتر وصل کنید که وزن مستقیم تریلر را نشان می دهد.
به یکی از اعداد بالا کافیست وصل شود چون وزن 1 و 2و3 یکی است

**Comment by mirmostafa** [comment]
#Tasks List

- [ ] #432

**Comment by mirmostafa** [comment]
ظاهرا در حال حاضر وجود دارد. اگر مشکل جای دیگری است، لطفا بیشتر توضیح دهید.
متشکرم
