### ISSUE TITLE
تغییرات در تب های مانیتورینگ

### ISSUE THREAD

**Issue by Akavoosi** [Moshaveran-IoT/GsTechCoreV1-GitLab#431]
### Repro Steps

در قسمت اطلاعات راننده و وزن تریلر می بایست اسکرول ها حذف شود
همترازی بین ماژولها برقرار باشد
و موارد دیگری که باید در جلسه ای مطرح کنم

**Comment by Maedehoseyni** [comment]
- [ ] در قسمت اطلاعات راننده اسکرول حذف گردد
- [ ] در تب وزن و دما اسکرول حذف گردد

**Comment by Maedehoseyni** [comment]
اسکرول فقط در تب های سرویس دوره ای ،ecu  و دیاگ فعال است
