### ISSUE TITLE
حذف دیتاهای پرت

### ISSUE THREAD

**Issue by Akavoosi** [Moshaveran-IoT/GsTechCoreV1-GitLab#466]
### Repro Steps

در نقشه همچنان دیتاهای چرت دیده می شود. مقرر شد الگوریتمی برای این منظور طراحی شود.

**Comment by mirmostafa** [comment]
سرویس مربوطه Down بود. Up کردم، اکی شد.

**Comment by Akavoosi** [comment]
برای وزن چرا همچنان دیتاهای پرت داریم
خودرو پاسارگاد با پلاک 676



![Image](https://github.com/user-attachments/assets/56508b08-5273-4c91-b220-cb61011fc93a)

**Comment by mirmostafa** [comment]
وقت بخیر.
من اطلاعاتی که زحمتش رو کشیدید رو نمیبینم!!!
![image](https://github.com/user-attachments/assets/31a62af6-115f-4a45-91a3-0c3bfc992acd)
آیا روی 62 خودمونه؟
@Akavoosi
