### ISSUE TITLE
آپدیت پی ام شرکت پرنیان

### ISSUE THREAD

**Issue by Akavoosi** [Moshaveran-IoT/GsTechCoreV1-GitLab#474]
### Description

مطابق تغییرات اعلام شده شرکت پرنیان پس از اخذ تاییدیه از مهرداد انجام شود.

**Comment by Maedehoseyni** [comment]
- [ ] فایل چک لیست روزانه قبلا ارسال شده است در حال حاضر قابل مشاهد نمی باشد
- [ ]  فایل سرویس دوره ای قبلا ارسال شده است در حال حاضر قابل مشاهد نمی باشد
- [ ] تفکیک راننده و پرسنل در منوی کاربران
- [ ]  نام سرویس دوره ای در قسمت عملیات به ثبت سرویس دوره ای تغییر نام داده شود
- [ ]  امکان ورود کاربران به پنل با Enter
- [ ] در قسمت خسارات امکان فراهم شود که سقف بیمه و باقی مانده خسارات به تفکیک خودرو قابل رویت و گزارشگیری باشد
- [ ]  در قسمت بیمه ثالث و بدنه ستون تعهدات مالی اضافه شود
- [ ] امکان بارگذاری اکسل و ویرایش گروهی در قسمت سیستم من جمله بیمه، سرویس دوره ای ،پروانه فعالیت و سایر قسمت های دیگر سیستم برای کاربر امکان پذیر باشد
- [ ] پرسنل براساس نمایندگی های که مشغول بکار می باشد دسته بندی شوند که هنگام ورود به سیستم فقط اطلاعات مختص خود آن نمایندگی را مشاهد نماید
- [ ] در قسمت فرم درخواست و پذیرش خودرو شرایط فراهم شود که هر یوزر با کاربری خود لاگین می کند به صورت پیش فرض کادر مخصوص به آن کاربر تکمیل شود امکان ویرایش برای کاربران پایین تر از سطح کارشناس فنی غیر ممکن باش

**Comment by Maedehoseyni** [comment]
![Image](https://github.com/user-attachments/assets/2ee1d878-e5ea-46cd-9788-a611935b84fb)
![Image](https://github.com/user-attachments/assets/051ecf1d-0568-4a9f-b8c3-edf3366f919f)
تغییرات باید مطابق عکس ها انجام گردد

**Comment by Akavoosi** [comment]
تغییرات خواسته شده پرنیان تا کنون در صورت تصویب اعمال شود و طی جلسه ای با آقای خدارضایی هماهنگ شود برای ادامه کار
