### ISSUE TITLE
دیتاهای پرت جی پی اس / پارت دوم

### ISSUE THREAD

**Issue by Akavoosi** [Moshaveran-IoT/GsTechCoreV1-GitLab#510]
### Repro Steps

در قسمت اول ما با محدود کردن نقشه ایران دیتاهای پرت را تشخیص و فلگ گذاری کردیم در این قسمت می بایست دیتاها را به نحوی مدیریت کنیم که روی نقشه منظم و تمییز نمایش داده شوند

![Image](https://github.com/user-attachments/assets/ea796533-e69a-4e41-9a2e-be23b7369252)

**Comment by mirmostafa** [comment]
در حال حاضر، سرویس نگهداری سه عملیات را روی "GPS ماشین" انجام می‌دهد:

- حذف داده‌های نادرست
- اطلاعات GPS خارج از محدوده ایران
- اطلاعات GPS نشان‌دهنده سرعت‌های غیرمنطقی که سقف سرعت منطقی قابل تنظیم است.

اگر مدیر محترم محصول (@Moshaveran-IoT/product-owners) تمایل داشته باشند، می‌توان بر روی این مشکل (و سایر مشکلات مشابه احتمالی) تمرکز کرد و راه‌حل مناسبی را برای حل آن یافت و پیاده‌سازی نمود.

**Comment by mirmostafa** [comment]
مشکل مشابه: #242
