### ISSUE TITLE
نشان ندادن نمودار و مقادیر دما در تب دما مانیتورینگ

### ISSUE THREAD

**Issue by Maedehoseyni** [Moshaveran-IoT/GsTechCoreV1-GitLab#511]

**Comment by Maedehoseyni** [comment]
- [ ] درست کردن و نرمالایز کردن دیتاهای دما 
- [ ] نمایش مقدار اخر در تب دما مانیتورینگ
- [ ]

**Comment by Akavoosi** [comment]
همچنان دما را نشان نمی دهد.

![Image](https://github.com/user-attachments/assets/e5d17b78-59b0-4f0b-97ab-a869e732bc5d)
