### ISSUE TITLE
اطلاعات در تب اطلاعات راننده بدون اسکرول مرتب شود

### ISSUE THREAD

**Issue by Akavoosi** [Moshaveran-IoT/GsTechCoreV1-GitLab#528]
### Repro Steps

مطابق تصویر زیر می بایست اسکرول تب حذف شود 

![Image](https://github.com/user-attachments/assets/5178352e-bd9c-4fe0-921a-d8eaf89ca6ff)

**Comment by Akavoosi** [comment]
اسم راننده در این تب حذف شده یا از همان اول هم نبوده؟ بنظر باید اضافه شود.

**Comment by mirmostafa** [comment]
مربوط به فرانت است

**Comment by Maedehoseyni** [comment]
اسم شخص در سمت راست هست و از اول نبوده
