### ISSUE TITLE
تغییرات در تب اطلاعات راننده مانیتورینگ جهت نشان دادن سرعت و باک و دور موتور

### ISSUE THREAD

**Issue by Akavoosi** [Moshaveran-IoT/GsTechCoreV1-GitLab#529]
### Description

چند تغییر عمده می بایست صورت پذیرد.
1- اگر خودرو تریلی بود باید فقط سرعت را نشان دهد و آنرا از جی پی اس دریافت کند و دور موتور و باک نباید نشان داده شود. 2- اگر خودرو کشنده و یا کامیونت بود قائدتا باید نمایش دهد مگر اینکه این اطلاعات موجود نباشد در واقع باید بشکل داینامیک این موضوع رصد شود

**Comment by Maedehoseyni** [comment]
ماشین اگر تریلی بود دایره باک و دور موتور حذف گردید
