### ISSUE TITLE
خطا در تشخیص صحیح رنگ بشکه وزن در مانیتورینگ

### ISSUE THREAD

**Issue by Akavoosi** [Moshaveran-IoT/GsTechCoreV1-GitLab#582]
### Repro Steps

می بایست بین عدد کمترین وزن و عدد حداقل بار برای نشان دادن پر بودن ماشین تفاوت قایل شد. بنابر این در قسمت تعریف وسیله نقلیه می بایست گزینه ای برای نشان دادن حداقل عدد برای پر نشان دادن خودرو اضافه شود که خودروهای دارای وزن برای نشان دادن پر و خالی بودن از آن عدد پیروی کنند.

![Image](https://github.com/user-attachments/assets/76480e9d-c9a6-4eb0-a3e9-877f278d5a89)

### Relevant log output

```shell

```

**Comment by mirmostafa** [comment]
قرار شد در Maintenance Service، بجای خواندن مستقیم از جدول `VehicleType`، داده‌ها از جدول `J1939` خوانده شوند.

**Comment by Akavoosi** [comment]
مقرر شد بین 4000 تا 32000 وزن ثابت تریلی با بار و بدون بار در نظر گرفته شود 
و برای پر و خالی بودن از ایتمهای خالی تعریف وسیله نقلیه استفاده شود

**Comment by Akavoosi** [comment]
چک شد 
اوکی است
