### ISSUE TITLE
ایجاد گزارش بروز رسانی در اپلیکیشن مشابه تصویر

### ISSUE THREAD

**Issue by Akavoosi** [Moshaveran-IoT/GsTechCoreV1-GitLab#584]
### Repro Steps

در جلسه ای می بایست این موضوع را مطرح و روشی را مصوب کنیم.
![Image](https://github.com/user-attachments/assets/06b81f2b-3a36-4017-98ae-6588628b0c12)

### Relevant log output

```shell

```

**Comment by mirmostafa** [comment]
این ایشو، تکراری است. [(پشتیبانی از Versioning)](#566 )
لطفا روند پیشرفت را در [پشتیبانی از Versioning](#566 ) دنبال کنید

**Comment by Akavoosi** [comment]
پیشنهاد میکنم بجای سه رقم آخر بصورت تصادفی مطابق Major.Minor.Patch اجرا شود
مثلا 234 یعنی دو تغییر عمده / 5 تغییر جزیی و 4 مثلا رفع اشکال 

در این خصوص با مائده به جمع بندی برسید و به من اطلاع بدید

**Comment by Maedehoseyni** [comment]
ورژن بر اساس نوع تغییرات کاملا اشنباه است اولا تعیین نوع بسیار دشوار است و اگر تعداد یک نوع خطا به 20 تا برسه چی عدد 4 رقمی میشه کاملا اشتباهه این مورد از لحاظ فنی رد است .

**Comment by mirmostafa** [comment]
بر فرض، در یک release، "مثلا 234 یعنی دو تغییر عمده / 5 تغییر جزیی و 4 مثلا رفع اشکال" داریم. اگر درست در release بعدی "مثلا 234 یعنی دو تغییر عمده / 5 تغییر جزیی و 4 مثلا رفع اشکال" داشته باشیم، آیا هر دو release، نسخه مشابه خواهند داشت؟

**Comment by mirmostafa** [comment]
@Akavoosi
