### ISSUE TITLE
منطق گزارش خلاصه وزن چیست؟

### ISSUE THREAD

**Issue by Akavoosi** [Moshaveran-IoT/GsTechCoreV1-GitLab#621]
![Image](https://github.com/user-attachments/assets/e9f87c59-6007-411d-9e07-54315bb8bf21)

لطفا این موضوع را بگید تا بدونم چون متوجه نشدم

**Comment by mirmostafa** [comment]
در [Wiki](https://github.com/Moshaveran-IoT/GsTechCoreV1-GitLab/wiki) در بخش [گزارش وزن](https://github.com/Moshaveran-IoT/GsTechCoreV1-GitLab/wiki/%DA%AF%D8%B2%D8%A7%D8%B1%D8%B4-%D9%88%D8%B2%D9%86) توضیح داده شد.
جناب @Akavoosi  لطفا بررسی بفرمایید.
