### ISSUE TITLE
خطا در انتخاب نوع تعمیرگاه در گزارش pm (درخواس تعمیرات)

### ISSUE THREAD

**Issue by Akavoosi** [Moshaveran-IoT/GsTechCoreV1-GitLab#625]
### Repro Steps

هنگامیکه تعمیرگاه کلیک می شود اسامی راننده ها و خودرو ها باز می شود

![Image](https://github.com/user-attachments/assets/0b1868c9-095e-4e71-8478-60fe21620833)

### Relevant log output

```shell

```

**Comment by Maedehoseyni** [comment]
این تعمیرگاه منظور شخص فنی اونجاست نه خود ماهیت

**Comment by Akavoosi** [comment]
یادمان باشد در تغییرات قسمت پی ام عنوان آن درست شود
@Maedehoseyni
